development:
  host: localhost
  database: rent_development

test:
  host: localhost
  database: rent_test

# set these environment variables on your prod server
production:
  host: localhost #<%= ENV['MONGOID_HOST'] %>
  database: rent_production # <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
